### ISSUE TITLE
[Bug] Database Issues

### ISSUE THREAD

**Issue by TheWylot** [MherZaqaryan/BedWars1058-Cosmetics-Issues#106]
**Describe the bug**
Database Connection, Performance issues are really high, as i mentioned on Discord Server, on java 11 and java 17 it gives us Timeout and Saving issues. but querying database very well

**Server Information (please complete the following information):**
 - OS: Ubuntu 22.04
 - Server Software: CarbonSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: Custom Fork of 23.3 & every stable release from Andrei
 - Cosmetics Addon: 1.1.2

**Comment by MherZaqaryan** [comment]
This issue is marked invalid because it lacks information on how you determined that the performance issues were coming from Cosmetics.

Please note, if you still believe it's a Cosmetic issue, and if you have a higher player capacity, make sure to extend your database query capacity to avoid performance issues (this was also discussed on my Discord server).
